POST http://localhost:3000/api/category
Content-Type: application/json

{
    "factoryName":"Tata steel",
    "totalTargetSales":40000000,
    "currentSales":3000000
}

###
PUT http://localhost:3000/api/category/61c819fb59381c0f90f91d15
Content-Type: application/json

{
    "totalTargetSales":40000000,
    "currentSales":30000000
}

###
GET http://localhost:3000/api/category/